### PR TITLE
feat: Support Realtime V2

### PR DESCRIPTION
**Pull request by filipecabaco**
## What kind of change does this PR introduce?

* Adds support for Realtime V2 by propagating the configuration on the first connect message.
* Adds example project for quick testing during development

### CODE REVIEW

**Comment by bitnom** [comment]
Which version is currently live on supabase cloud?

**Comment by nicognaW** [comment]
> Which version is currently live on supabase cloud?

The supabase cloud should support both v1 and v2, but Broadcast and Presence are v2-only features and in [beta status](https://github.com/supabase/realtime?tab=readme-ov-file#status).

I'm starting a project with AI training using supabase realtime as the job queue system, I'm currently using `filipecabaco/realtime-py@feat/support-realtime-v2#egg=realtime` for v2 features, it would be helpful if supabase-community staffs could merge this PR.

@silentworks @anand2312

**Comment by silentworks** [comment]
@nicognaW I'm not a staff but a contributor to this repo. This cannot be merged as the OP has left it in draft mode as it's not complete from what I have gathered.

**Comment by filipecabaco** [comment]
Yes still in draft mode. We still want to do some improvements as the developer experience of the current branch is still subpar and we really want to ensure that it's in a better state.

In fact it would be extremely useful to receive feedback on that PR so we can start to improve it so it's merge worthy

**Comment by grdsdev** [comment]
This was implemented in https://github.com/supabase/realtime-py/pull/178, I'll close it.

**Pull request closed without merging**
