### PR TITLE
refactored code and added logging

### PR DESCRIPTION
**Pull request by prettyirrelevant**

### CODE REVIEW

**Comment by lionellloh** [comment]
Looks good to me, thanks for helping!

**Comment by lionellloh** [comment]
Looks good to me, thanks for helping! (ignore the close, accident)

**Comment by prettyirrelevant** [comment]
Glad I could help. Can this be wrapped into **supabase-py**?

**Comment by lionellloh** [comment]
@prettyirrelevant I believe @J0 is working on it. Maybe he can use some help. :)

**Pull request merged**
